apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-scripts
  namespace: gdx-orde-perf
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class MyUser(HttpUser):
        wait_time = between(1, 3)
        host = "https://tricentis.com"

        @task
        def open_homepage(self):
            self.client.get("/")

        @task
        def open_products(self):
            self.client.get("/products")

        @task
        def open_about(self):
            self.client.get("/about")
